// packages/sifo-mplg-drag-vue/src/editor/header.vue
<template>
  <div class="sifo-mplg-drag-header">
    <div class="sifo-mplg-drag-title">{{title || 'Sifo拖拽插件'}}</div>
    <div class="sifo-mplg-drag-tool">
      <button class="sifo-mplg-drag-btn" @click="delSelectedNode">
        删除选中节点
      </button>
      <button class="sifo-mplg-drag-btn primary" @click="save">保存</button>
    </div>
  </div>
</template>
<script>
export default {
  name: "sifo-drag-editor-header",
  methods: {
    save: function (event) {
      const schema = this.getSchema();
      this.$emit("onSave", schema);
    },
    delSelectedNode: function () {
      if (this.selectedId) {
        this.$emit("deleteNode", this.selectedId);
      }
    },
  },
  props: ["title", "selectedId", "getSchema"],
};
</script>

// packages/sifo-mplg-drag-react/src/editor/header.jsx
import React from 'react';
import PropTypes from 'prop-types';

const Header = props => {
  const { deleteNode, selectedId, getSchema, onSave } = props;
  const save = () => {
    const schema = getSchema();
    onSave && onSave(schema);
  };
  const delSelectedNode = () => {
    if (selectedId) {
      deleteNode(selectedId);
    }
  };
  return (
    <div className="sifo-mplg-drag-header">
      <div className="sifo-mplg-drag-title">Sifo拖拽插件</div>
      <div className="sifo-mplg-drag-tool">
        <button className="sifo-mplg-drag-btn" onClick={delSelectedNode}>删除选中节点</button>
        <button className="sifo-mplg-drag-btn primary" onClick={save}>保存</button>
      </div>
    </div>
  );
};
Header.propTypes = {
  deleteNode: PropTypes.func.isRequired,
  selectedId: PropTypes.string,
  getSchema: PropTypes.func.isRequired,
  onSave: PropTypes.func,
};
Header.defaultProps = {
  selectedId: '',
  onSave: (e) => { console.log('onSave', e);}
};

export default Header;
